INSERT INTO `xfguestbook_country` VALUES (1, 'it-ab', 'Abruzzo');
INSERT INTO `xfguestbook_country` VALUES (2, 'it-ba', 'Basilicata');
INSERT INTO `xfguestbook_country` VALUES (3, 'it-ca', 'Calabria');
INSERT INTO `xfguestbook_country` VALUES (4, 'it-cm', 'Campania');
INSERT INTO `xfguestbook_country` VALUES (5, 'it-em', 'Emilia Romagna');
INSERT INTO `xfguestbook_country` VALUES (6, 'it-fr', 'Friuli');
INSERT INTO `xfguestbook_country` VALUES (7, 'it-la', 'Lazio');
INSERT INTO `xfguestbook_country` VALUES (8, 'it-li', 'Liguria');
INSERT INTO `xfguestbook_country` VALUES (9, 'it-lo', 'Lombardia');
INSERT INTO `xfguestbook_country` VALUES (10, 'it-ma', 'Marche');
INSERT INTO `xfguestbook_country` VALUES (11, 'it-mo', 'Molise');
INSERT INTO `xfguestbook_country` VALUES (12, 'it-pi', 'Piemonte');
INSERT INTO `xfguestbook_country` VALUES (13, 'it-pu', 'Puglia');
INSERT INTO `xfguestbook_country` VALUES (14, 'it-sa', 'Sardegna');
INSERT INTO `xfguestbook_country` VALUES (15, 'it-si', 'Sicilia');
INSERT INTO `xfguestbook_country` VALUES (16, 'it-to', 'Toscana');
INSERT INTO `xfguestbook_country` VALUES (17, 'it-tr', 'Trentino Alto Adige');
INSERT INTO `xfguestbook_country` VALUES (18, 'it-um', 'Umbria');
INSERT INTO `xfguestbook_country` VALUES (19, 'it-va', 'Valle d\'Aosta');
INSERT INTO `xfguestbook_country` VALUES (20, 'it-ve', 'Veneto');
