#
# Contenu de la table `xfguestbook_country` 
#

INSERT INTO `xfguestbook_country` VALUES (1, 'AF', 'AFGHANISTAN');
INSERT INTO `xfguestbook_country` VALUES (2, 'AX', 'ALAND ISLANDS');
INSERT INTO `xfguestbook_country` VALUES (3, 'AL', 'ALBANIA');
INSERT INTO `xfguestbook_country` VALUES (4, 'DZ', 'ALGERIA');
INSERT INTO `xfguestbook_country` VALUES (5, 'AS', 'AMERICAN SAMOA');
INSERT INTO `xfguestbook_country` VALUES (6, 'AD', 'ANDORRA');
INSERT INTO `xfguestbook_country` VALUES (7, 'AO', 'ANGOLA');
INSERT INTO `xfguestbook_country` VALUES (8, 'AI', 'ANGUILLA');
INSERT INTO `xfguestbook_country` VALUES (9, 'AQ', 'ANTARCTICA');
INSERT INTO `xfguestbook_country` VALUES (10, 'AG', 'ANTIGUA AND BARBUDA');
INSERT INTO `xfguestbook_country` VALUES (11, 'AR', 'ARGENTINA');
INSERT INTO `xfguestbook_country` VALUES (12, 'AM', 'ARMENIA');
INSERT INTO `xfguestbook_country` VALUES (13, 'AW', 'ARUBA');
INSERT INTO `xfguestbook_country` VALUES (14, 'AU', 'AUSTRALIA');
INSERT INTO `xfguestbook_country` VALUES (15, 'AT', 'AUSTRIA');
INSERT INTO `xfguestbook_country` VALUES (16, 'AZ', 'AZERBAIJAN');
INSERT INTO `xfguestbook_country` VALUES (17, 'BS', 'BAHAMAS');
INSERT INTO `xfguestbook_country` VALUES (18, 'BH', 'BAHRAIN');
INSERT INTO `xfguestbook_country` VALUES (19, 'BD', 'BANGLADESH');
INSERT INTO `xfguestbook_country` VALUES (20, 'BB', 'BARBADOS');
INSERT INTO `xfguestbook_country` VALUES (21, 'BY', 'BELARUS');
INSERT INTO `xfguestbook_country` VALUES (22, 'BE', 'BELGIUM');
INSERT INTO `xfguestbook_country` VALUES (23, 'BZ', 'BELIZE');
INSERT INTO `xfguestbook_country` VALUES (24, 'BJ', 'BENIN');
INSERT INTO `xfguestbook_country` VALUES (25, 'BM', 'BERMUDA');
INSERT INTO `xfguestbook_country` VALUES (26, 'BT', 'BHUTAN');
INSERT INTO `xfguestbook_country` VALUES (27, 'BO', 'BOLIVIA');
INSERT INTO `xfguestbook_country` VALUES (28, 'BA', 'BOSNIA AND HERZEGOVINA');
INSERT INTO `xfguestbook_country` VALUES (29, 'BW', 'BOTSWANA');
INSERT INTO `xfguestbook_country` VALUES (30, 'BV', 'BOUVET ISLAND');
INSERT INTO `xfguestbook_country` VALUES (31, 'BR', 'BRAZIL');
INSERT INTO `xfguestbook_country` VALUES (32, 'IO', 'BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO `xfguestbook_country` VALUES (33, 'BN', 'BRUNEI DARUSSALAM');
INSERT INTO `xfguestbook_country` VALUES (34, 'BG', 'BULGARIA');
INSERT INTO `xfguestbook_country` VALUES (35, 'BF', 'BURKINA FASO');
INSERT INTO `xfguestbook_country` VALUES (36, 'BI', 'BURUNDI');
INSERT INTO `xfguestbook_country` VALUES (37, 'KH', 'CAMBODIA');
INSERT INTO `xfguestbook_country` VALUES (38, 'CM', 'CAMEROON');
INSERT INTO `xfguestbook_country` VALUES (39, 'CA', 'CANADA');
INSERT INTO `xfguestbook_country` VALUES (40, 'CV', 'CAPE VERDE');
INSERT INTO `xfguestbook_country` VALUES (41, 'KY', 'CAYMAN ISLANDS');
INSERT INTO `xfguestbook_country` VALUES (42, 'CF', 'CENTRAL AFRICAN REPUBLIC');
INSERT INTO `xfguestbook_country` VALUES (43, 'TD', 'CHAD');
INSERT INTO `xfguestbook_country` VALUES (44, 'CL', 'CHILE');
INSERT INTO `xfguestbook_country` VALUES (45, 'CN', 'CHINA');
INSERT INTO `xfguestbook_country` VALUES (46, 'CX', 'CHRISTMAS ISLAND');
INSERT INTO `xfguestbook_country` VALUES (47, 'CC', 'COCOS (KEELING) ISLANDS');
INSERT INTO `xfguestbook_country` VALUES (48, 'CO', 'COLOMBIA');
INSERT INTO `xfguestbook_country` VALUES (49, 'KM', 'COMOROS');
INSERT INTO `xfguestbook_country` VALUES (50, 'CG', 'CONGO');
INSERT INTO `xfguestbook_country` VALUES (51, 'CD', 'CONGO, THE DEMOCRATIC REPUBLIC');
INSERT INTO `xfguestbook_country` VALUES (52, 'CK', 'COOK ISLANDS');
INSERT INTO `xfguestbook_country` VALUES (53, 'CR', 'COSTA RICA');
INSERT INTO `xfguestbook_country` VALUES (54, 'CI', 'COTE D\'IVOIRE');
INSERT INTO `xfguestbook_country` VALUES (55, 'HR', 'CROATIA');
INSERT INTO `xfguestbook_country` VALUES (56, 'CU', 'CUBA');
INSERT INTO `xfguestbook_country` VALUES (57, 'CY', 'CYPRUS');
INSERT INTO `xfguestbook_country` VALUES (58, 'CZ', 'CZECH REPUBLIC');
INSERT INTO `xfguestbook_country` VALUES (59, 'DK', 'DENMARK');
INSERT INTO `xfguestbook_country` VALUES (60, 'DJ', 'DJIBOUTI');
INSERT INTO `xfguestbook_country` VALUES (61, 'DM', 'DOMINICA');
INSERT INTO `xfguestbook_country` VALUES (62, 'DO', 'DOMINICAN REPUBLIC');
INSERT INTO `xfguestbook_country` VALUES (63, 'EC', 'ECUADOR');
INSERT INTO `xfguestbook_country` VALUES (64, 'EG', 'EGYPT');
INSERT INTO `xfguestbook_country` VALUES (65, 'SV', 'EL SALVADOR');
INSERT INTO `xfguestbook_country` VALUES (66, 'GQ', 'EQUATORIAL GUINEA');
INSERT INTO `xfguestbook_country` VALUES (67, 'ER', 'ERITREA');
INSERT INTO `xfguestbook_country` VALUES (68, 'EE', 'ESTONIA');
INSERT INTO `xfguestbook_country` VALUES (69, 'ET', 'ETHIOPIA');
INSERT INTO `xfguestbook_country` VALUES (70, 'FK', 'FALKLAND ISLANDS (MALVINAS)');
INSERT INTO `xfguestbook_country` VALUES (71, 'FO', 'FAROE ISLANDS');
INSERT INTO `xfguestbook_country` VALUES (72, 'FJ', 'FIJI');
INSERT INTO `xfguestbook_country` VALUES (73, 'FI', 'FINLAND');
INSERT INTO `xfguestbook_country` VALUES (74, 'FR', 'FRANCE');
INSERT INTO `xfguestbook_country` VALUES (75, 'GF', 'FRENCH GUIANA');
INSERT INTO `xfguestbook_country` VALUES (76, 'PF', 'FRENCH POLYNESIA');
INSERT INTO `xfguestbook_country` VALUES (77, 'TF', 'FRENCH SOUTHERN TERRITORIES');
INSERT INTO `xfguestbook_country` VALUES (78, 'GA', 'GABON');
INSERT INTO `xfguestbook_country` VALUES (79, 'GM', 'GAMBIA');
INSERT INTO `xfguestbook_country` VALUES (80, 'GE', 'GEORGIA');
INSERT INTO `xfguestbook_country` VALUES (81, 'DE', 'GERMANY');
INSERT INTO `xfguestbook_country` VALUES (82, 'GH', 'GHANA');
INSERT INTO `xfguestbook_country` VALUES (83, 'GI', 'GIBRALTAR');
INSERT INTO `xfguestbook_country` VALUES (84, 'GR', 'GREECE');
INSERT INTO `xfguestbook_country` VALUES (85, 'GL', 'GREENLAND');
INSERT INTO `xfguestbook_country` VALUES (86, 'GD', 'GRENADA');
INSERT INTO `xfguestbook_country` VALUES (87, 'GP', 'GUADELOUPE');
INSERT INTO `xfguestbook_country` VALUES (88, 'GU', 'GUAM');
INSERT INTO `xfguestbook_country` VALUES (89, 'GT', 'GUATEMALA');
INSERT INTO `xfguestbook_country` VALUES (90, 'GN', 'GUINEA');
INSERT INTO `xfguestbook_country` VALUES (91, 'GW', 'GUINEA-BISSAU');
INSERT INTO `xfguestbook_country` VALUES (92, 'GY', 'GUYANA');
INSERT INTO `xfguestbook_country` VALUES (93, 'HT', 'HAITI');
INSERT INTO `xfguestbook_country` VALUES (94, 'HM', 'HEARD ISLAND AND MCDONALD ISLA');
INSERT INTO `xfguestbook_country` VALUES (95, 'VA', 'HOLY SEE (VATICAN CITY STATE)');
INSERT INTO `xfguestbook_country` VALUES (96, 'HN', 'HONDURAS');
INSERT INTO `xfguestbook_country` VALUES (97, 'HK', 'HONG KONG');
INSERT INTO `xfguestbook_country` VALUES (98, 'HU', 'HUNGARY');
INSERT INTO `xfguestbook_country` VALUES (99, 'IS', 'ICELAND');
INSERT INTO `xfguestbook_country` VALUES (100, 'IN', 'INDIA');
INSERT INTO `xfguestbook_country` VALUES (101, 'ID', 'INDONESIA');
INSERT INTO `xfguestbook_country` VALUES (102, 'IR', 'IRAN, ISLAMIC REPUBLIC OF');
INSERT INTO `xfguestbook_country` VALUES (103, 'IQ', 'IRAQ');
INSERT INTO `xfguestbook_country` VALUES (104, 'IE', 'IRELAND');
INSERT INTO `xfguestbook_country` VALUES (105, 'IL', 'ISRAEL');
INSERT INTO `xfguestbook_country` VALUES (106, 'IT', 'ITALY');
INSERT INTO `xfguestbook_country` VALUES (107, 'JM', 'JAMAICA');
INSERT INTO `xfguestbook_country` VALUES (108, 'JP', 'JAPAN');
INSERT INTO `xfguestbook_country` VALUES (109, 'JO', 'JORDAN');
INSERT INTO `xfguestbook_country` VALUES (110, 'KZ', 'KAZAKHSTAN');
INSERT INTO `xfguestbook_country` VALUES (111, 'KE', 'KENYA');
INSERT INTO `xfguestbook_country` VALUES (112, 'KI', 'KIRIBATI');
INSERT INTO `xfguestbook_country` VALUES (113, 'KP', 'KOREA, DEMOCRATIC PEOPLE\'S REP');
INSERT INTO `xfguestbook_country` VALUES (114, 'KR', 'KOREA, REPUBLIC OF');
INSERT INTO `xfguestbook_country` VALUES (115, 'KW', 'KUWAIT');
INSERT INTO `xfguestbook_country` VALUES (116, 'KG', 'KYRGYZSTAN');
INSERT INTO `xfguestbook_country` VALUES (117, 'LA', 'LAO PEOPLE\'S DEMOCRATIC REPUBL');
INSERT INTO `xfguestbook_country` VALUES (118, 'LV', 'LATVIA');
INSERT INTO `xfguestbook_country` VALUES (119, 'LB', 'LEBANON');
INSERT INTO `xfguestbook_country` VALUES (120, 'LS', 'LESOTHO');
INSERT INTO `xfguestbook_country` VALUES (121, 'LR', 'LIBERIA');
INSERT INTO `xfguestbook_country` VALUES (122, 'LY', 'LIBYAN ARAB JAMAHIRIYA');
INSERT INTO `xfguestbook_country` VALUES (123, 'LI', 'LIECHTENSTEIN');
INSERT INTO `xfguestbook_country` VALUES (124, 'LT', 'LITHUANIA');
INSERT INTO `xfguestbook_country` VALUES (125, 'LU', 'LUXEMBOURG');
INSERT INTO `xfguestbook_country` VALUES (126, 'MO', 'MACAO');
INSERT INTO `xfguestbook_country` VALUES (127, 'MK', 'MACEDONIA, THE FORMER YUGOSLAV');
INSERT INTO `xfguestbook_country` VALUES (128, 'MG', 'MADAGASCAR');
INSERT INTO `xfguestbook_country` VALUES (129, 'MW', 'MALAWI');
INSERT INTO `xfguestbook_country` VALUES (130, 'MY', 'MALAYSIA');
INSERT INTO `xfguestbook_country` VALUES (131, 'MV', 'MALDIVES');
INSERT INTO `xfguestbook_country` VALUES (132, 'ML', 'MALI');
INSERT INTO `xfguestbook_country` VALUES (133, 'MT', 'MALTA');
INSERT INTO `xfguestbook_country` VALUES (134, 'MH', 'MARSHALL ISLANDS');
INSERT INTO `xfguestbook_country` VALUES (135, 'MQ', 'MARTINIQUE');
INSERT INTO `xfguestbook_country` VALUES (136, 'MR', 'MAURITANIA');
INSERT INTO `xfguestbook_country` VALUES (137, 'MU', 'MAURITIUS');
INSERT INTO `xfguestbook_country` VALUES (138, 'YT', 'MAYOTTE');
INSERT INTO `xfguestbook_country` VALUES (139, 'MX', 'MEXICO');
INSERT INTO `xfguestbook_country` VALUES (140, 'FM', 'MICRONESIA, FEDERATED STATES O');
INSERT INTO `xfguestbook_country` VALUES (141, 'MD', 'MOLDOVA, REPUBLIC OF');
INSERT INTO `xfguestbook_country` VALUES (142, 'MC', 'MONACO');
INSERT INTO `xfguestbook_country` VALUES (143, 'MN', 'MONGOLIA');
INSERT INTO `xfguestbook_country` VALUES (144, 'MS', 'MONTSERRAT');
INSERT INTO `xfguestbook_country` VALUES (145, 'MA', 'MOROCCO');
INSERT INTO `xfguestbook_country` VALUES (146, 'MZ', 'MOZAMBIQUE');
INSERT INTO `xfguestbook_country` VALUES (147, 'MM', 'MYANMAR');
INSERT INTO `xfguestbook_country` VALUES (148, 'NA', 'NAMIBIA');
INSERT INTO `xfguestbook_country` VALUES (149, 'NR', 'NAURU');
INSERT INTO `xfguestbook_country` VALUES (150, 'NP', 'NEPAL');
INSERT INTO `xfguestbook_country` VALUES (151, 'NL', 'NETHERLANDS');
INSERT INTO `xfguestbook_country` VALUES (152, 'AN', 'NETHERLANDS ANTILLES');
INSERT INTO `xfguestbook_country` VALUES (153, 'NC', 'NEW CALEDONIA');
INSERT INTO `xfguestbook_country` VALUES (154, 'NZ', 'NEW ZEALAND');
INSERT INTO `xfguestbook_country` VALUES (155, 'NI', 'NICARAGUA');
INSERT INTO `xfguestbook_country` VALUES (156, 'NE', 'NIGER');
INSERT INTO `xfguestbook_country` VALUES (157, 'NG', 'NIGERIA');
INSERT INTO `xfguestbook_country` VALUES (158, 'NU', 'NIUE');
INSERT INTO `xfguestbook_country` VALUES (159, 'NF', 'NORFOLK ISLAND');
INSERT INTO `xfguestbook_country` VALUES (160, 'MP', 'NORTHERN MARIANA ISLANDS');
INSERT INTO `xfguestbook_country` VALUES (161, 'NO', 'NORWAY');
INSERT INTO `xfguestbook_country` VALUES (162, 'OM', 'OMAN');
INSERT INTO `xfguestbook_country` VALUES (163, 'PK', 'PAKISTAN');
INSERT INTO `xfguestbook_country` VALUES (164, 'PW', 'PALAU');
INSERT INTO `xfguestbook_country` VALUES (165, 'PS', 'PALESTINIAN TERRITORY, OCCUPIE');
INSERT INTO `xfguestbook_country` VALUES (166, 'PA', 'PANAMA');
INSERT INTO `xfguestbook_country` VALUES (167, 'PG', 'PAPUA NEW GUINEA');
INSERT INTO `xfguestbook_country` VALUES (168, 'PY', 'PARAGUAY');
INSERT INTO `xfguestbook_country` VALUES (169, 'PE', 'PERU');
INSERT INTO `xfguestbook_country` VALUES (170, 'PH', 'PHILIPPINES');
INSERT INTO `xfguestbook_country` VALUES (171, 'PN', 'PITCAIRN');
INSERT INTO `xfguestbook_country` VALUES (172, 'PL', 'POLAND');
INSERT INTO `xfguestbook_country` VALUES (173, 'PT', 'PORTUGAL');
INSERT INTO `xfguestbook_country` VALUES (174, 'PR', 'PUERTO RICO');
INSERT INTO `xfguestbook_country` VALUES (175, 'QA', 'QATAR');
INSERT INTO `xfguestbook_country` VALUES (176, 'RE', 'REUNION');
INSERT INTO `xfguestbook_country` VALUES (177, 'RO', 'ROMANIA');
INSERT INTO `xfguestbook_country` VALUES (178, 'RU', 'RUSSIAN FEDERATION');
INSERT INTO `xfguestbook_country` VALUES (179, 'RW', 'RWANDA');
INSERT INTO `xfguestbook_country` VALUES (180, 'SH', 'SAINT HELENA');
INSERT INTO `xfguestbook_country` VALUES (181, 'KN', 'SAINT KITTS AND NEVIS');
INSERT INTO `xfguestbook_country` VALUES (182, 'LC', 'SAINT LUCIA');
INSERT INTO `xfguestbook_country` VALUES (183, 'PM', 'SAINT PIERRE AND MIQUELON');
INSERT INTO `xfguestbook_country` VALUES (184, 'VC', 'SAINT VINCENT AND THE GRENADIN');
INSERT INTO `xfguestbook_country` VALUES (185, 'WS', 'SAMOA');
INSERT INTO `xfguestbook_country` VALUES (186, 'SM', 'SAN MARINO');
INSERT INTO `xfguestbook_country` VALUES (187, 'ST', 'SAO TOME AND PRINCIPE');
INSERT INTO `xfguestbook_country` VALUES (188, 'SA', 'SAUDI ARABIA');
INSERT INTO `xfguestbook_country` VALUES (189, 'SN', 'SENEGAL');
INSERT INTO `xfguestbook_country` VALUES (190, 'CS', 'SERBIA AND MONTENEGRO');
INSERT INTO `xfguestbook_country` VALUES (191, 'SC', 'SEYCHELLES');
INSERT INTO `xfguestbook_country` VALUES (192, 'SL', 'SIERRA LEONE');
INSERT INTO `xfguestbook_country` VALUES (193, 'SG', 'SINGAPORE');
INSERT INTO `xfguestbook_country` VALUES (194, 'SK', 'SLOVAKIA');
INSERT INTO `xfguestbook_country` VALUES (195, 'SI', 'SLOVENIA');
INSERT INTO `xfguestbook_country` VALUES (196, 'SB', 'SOLOMON ISLANDS');
INSERT INTO `xfguestbook_country` VALUES (197, 'SO', 'SOMALIA');
INSERT INTO `xfguestbook_country` VALUES (198, 'ZA', 'SOUTH AFRICA');
INSERT INTO `xfguestbook_country` VALUES (199, 'GS', 'SOUTH GEORGIA AND THE SOUTH SA');
INSERT INTO `xfguestbook_country` VALUES (200, 'ES', 'SPAIN');
INSERT INTO `xfguestbook_country` VALUES (201, 'LK', 'SRI LANKA');
INSERT INTO `xfguestbook_country` VALUES (202, 'SD', 'SUDAN');
INSERT INTO `xfguestbook_country` VALUES (203, 'SR', 'SURINAME');
INSERT INTO `xfguestbook_country` VALUES (204, 'SJ', 'SVALBARD AND JAN MAYEN');
INSERT INTO `xfguestbook_country` VALUES (205, 'SZ', 'SWAZILAND');
INSERT INTO `xfguestbook_country` VALUES (206, 'SE', 'SWEDEN');
INSERT INTO `xfguestbook_country` VALUES (207, 'CH', 'SWITZERLAND');
INSERT INTO `xfguestbook_country` VALUES (208, 'SY', 'SYRIAN ARAB REPUBLIC');
INSERT INTO `xfguestbook_country` VALUES (209, 'TW', 'TAIWAN');
INSERT INTO `xfguestbook_country` VALUES (210, 'TJ', 'TAJIKISTAN');
INSERT INTO `xfguestbook_country` VALUES (211, 'TZ', 'TANZANIA, UNITED REPUBLIC OF');
INSERT INTO `xfguestbook_country` VALUES (212, 'TH', 'THAILAND');
INSERT INTO `xfguestbook_country` VALUES (213, 'TL', 'TIMOR-LESTE');
INSERT INTO `xfguestbook_country` VALUES (214, 'TG', 'TOGO');
INSERT INTO `xfguestbook_country` VALUES (215, 'TK', 'TOKELAU');
INSERT INTO `xfguestbook_country` VALUES (216, 'TO', 'TONGA');
INSERT INTO `xfguestbook_country` VALUES (217, 'TT', 'TRINIDAD AND TOBAGO');
INSERT INTO `xfguestbook_country` VALUES (218, 'TN', 'TUNISIA');
INSERT INTO `xfguestbook_country` VALUES (219, 'TR', 'TURKEY');
INSERT INTO `xfguestbook_country` VALUES (220, 'TM', 'TURKMENISTAN');
INSERT INTO `xfguestbook_country` VALUES (221, 'TC', 'TURKS AND CAICOS ISLANDS');
INSERT INTO `xfguestbook_country` VALUES (222, 'TV', 'TUVALU');
INSERT INTO `xfguestbook_country` VALUES (223, 'UG', 'UGANDA');
INSERT INTO `xfguestbook_country` VALUES (224, 'UA', 'UKRAINE');
INSERT INTO `xfguestbook_country` VALUES (225, 'AE', 'UNITED ARAB EMIRATES');
INSERT INTO `xfguestbook_country` VALUES (226, 'GB', 'UNITED KINGDOM');
INSERT INTO `xfguestbook_country` VALUES (227, 'US', 'UNITED STATES');
INSERT INTO `xfguestbook_country` VALUES (228, 'UM', 'UNITED STATES MINOR OUTLYING I');
INSERT INTO `xfguestbook_country` VALUES (229, 'UY', 'URUGUAY');
INSERT INTO `xfguestbook_country` VALUES (230, 'UZ', 'UZBEKISTAN');
INSERT INTO `xfguestbook_country` VALUES (231, 'VU', 'VANUATU');
INSERT INTO `xfguestbook_country` VALUES (232, 'VE', 'VENEZUELA');
INSERT INTO `xfguestbook_country` VALUES (233, 'VN', 'VIET NAM');
INSERT INTO `xfguestbook_country` VALUES (234, 'VG', 'VIRGIN ISLANDS, BRITISH');
INSERT INTO `xfguestbook_country` VALUES (235, 'VI', 'VIRGIN ISLANDS, U.S.');
INSERT INTO `xfguestbook_country` VALUES (236, 'WF', 'WALLIS AND FUTUNA');
INSERT INTO `xfguestbook_country` VALUES (237, 'EH', 'WESTERN SAHARA');
INSERT INTO `xfguestbook_country` VALUES (238, 'YE', 'YEMEN');
INSERT INTO `xfguestbook_country` VALUES (239, 'ZM', 'ZAMBIA');
INSERT INTO `xfguestbook_country` VALUES (240, 'ZW', 'ZIMBABWE');
