INSERT INTO `xfguestbook_country` VALUES (1, 'us-al', 'ALABAMA');
INSERT INTO `xfguestbook_country` VALUES (2, 'us-ak', 'ALASKA');
INSERT INTO `xfguestbook_country` VALUES (3, 'us-az', 'ARIZONA');
INSERT INTO `xfguestbook_country` VALUES (4, 'us-ar', 'ARKANSAS');
INSERT INTO `xfguestbook_country` VALUES (5, 'us-ca', 'CALIFORNIA');
INSERT INTO `xfguestbook_country` VALUES (6, 'us-co', 'COLORADO');
INSERT INTO `xfguestbook_country` VALUES (7, 'us-ct', 'CONNECTICUT');
INSERT INTO `xfguestbook_country` VALUES (8, 'us-de', 'DELAWARE');
INSERT INTO `xfguestbook_country` VALUES (9, 'us-fl', 'FLORIDA');
INSERT INTO `xfguestbook_country` VALUES (10, 'us-ga', 'GEORGIA');
INSERT INTO `xfguestbook_country` VALUES (11, 'us-hi', 'HAWAI');
INSERT INTO `xfguestbook_country` VALUES (12, 'us-id', 'IDAHO');
INSERT INTO `xfguestbook_country` VALUES (13, 'us-il', 'ILINOIS');
INSERT INTO `xfguestbook_country` VALUES (14, 'us-in', 'INDIANA');
INSERT INTO `xfguestbook_country` VALUES (15, 'us-ia', 'IOWA');
INSERT INTO `xfguestbook_country` VALUES (16, 'us-ks', 'KANSAS');
INSERT INTO `xfguestbook_country` VALUES (17, 'us-ky', 'KENTUCKY');
INSERT INTO `xfguestbook_country` VALUES (18, 'us-la', 'LOUISIANA');
INSERT INTO `xfguestbook_country` VALUES (19, 'us-me', 'MAINE');
INSERT INTO `xfguestbook_country` VALUES (20, 'us-md', 'MARYLAND');
INSERT INTO `xfguestbook_country` VALUES (21, 'us-ma', 'MASSACHUSSETS');
INSERT INTO `xfguestbook_country` VALUES (22, 'us-mi', 'MICHIGAN');
INSERT INTO `xfguestbook_country` VALUES (23, 'us-mn', 'MINNESOTA');
INSERT INTO `xfguestbook_country` VALUES (24, 'us-ms', 'MISSISSIPI');
INSERT INTO `xfguestbook_country` VALUES (25, 'us-mo', 'MISSOURI');
INSERT INTO `xfguestbook_country` VALUES (26, 'us-mt', 'MONTANA');
INSERT INTO `xfguestbook_country` VALUES (27, 'us-ne', 'NEBRASKA');
INSERT INTO `xfguestbook_country` VALUES (28, 'us-nv', 'NEVADA');
INSERT INTO `xfguestbook_country` VALUES (29, 'us-nh', 'NEW HAMPSHIRE');
INSERT INTO `xfguestbook_country` VALUES (30, 'us-nj', 'NEW JERSEY');
INSERT INTO `xfguestbook_country` VALUES (31, 'us-nm', 'NEW MEXICO');
INSERT INTO `xfguestbook_country` VALUES (32, 'us-ny', 'NEW YORK');
INSERT INTO `xfguestbook_country` VALUES (33, 'us-nc', 'NORTH CAROLINA');
INSERT INTO `xfguestbook_country` VALUES (34, 'us-nd', 'NORTH DAKOTA');
INSERT INTO `xfguestbook_country` VALUES (35, 'us-oh', 'OHIO');
INSERT INTO `xfguestbook_country` VALUES (36, 'us-ok', 'OKLAHOMA');
INSERT INTO `xfguestbook_country` VALUES (37, 'us-or', 'OREGON');
INSERT INTO `xfguestbook_country` VALUES (38, 'us-pa', 'PENNSYLVANIA');
INSERT INTO `xfguestbook_country` VALUES (39, 'us-ri', 'RHODE ISLAND');
INSERT INTO `xfguestbook_country` VALUES (40, 'us-sc', 'SOUTH CAROLINA');
INSERT INTO `xfguestbook_country` VALUES (41, 'us-sd', 'SOUTH DAKOTA');
INSERT INTO `xfguestbook_country` VALUES (42, 'us-tn', 'TENNESSEE');
INSERT INTO `xfguestbook_country` VALUES (43, 'us-tx', 'TEXAS');
INSERT INTO `xfguestbook_country` VALUES (44, 'us-ut', 'UTAH');
INSERT INTO `xfguestbook_country` VALUES (45, 'us-vt', 'VERMONT');
INSERT INTO `xfguestbook_country` VALUES (46, 'us-va', 'VIRGINIA');
INSERT INTO `xfguestbook_country` VALUES (47, 'us-wa', 'WASHINGTON');
INSERT INTO `xfguestbook_country` VALUES (48, 'us-wv', 'WEST VIRGINIA');
INSERT INTO `xfguestbook_country` VALUES (49, 'us-wi', 'WISCONSIN');
INSERT INTO `xfguestbook_country` VALUES (50, 'us-wy', 'WYOMING');
