INSERT INTO `xfguestbook_country` VALUES (1, 'fr-al', 'Alsace');
INSERT INTO `xfguestbook_country` VALUES (2, 'fr-aq', 'Aquitaine');
INSERT INTO `xfguestbook_country` VALUES (3, 'fr-au', 'Auvergne');
INSERT INTO `xfguestbook_country` VALUES (4, 'fr-bn', 'Basse-Normandie');
INSERT INTO `xfguestbook_country` VALUES (5, 'fr-bo', 'Bourgogne');
INSERT INTO `xfguestbook_country` VALUES (6, 'fr-br', 'Bretagne');
INSERT INTO `xfguestbook_country` VALUES (7, 'fr-ce', 'Centre');
INSERT INTO `xfguestbook_country` VALUES (8, 'fr-ca', 'Champagne-Ardennes');
INSERT INTO `xfguestbook_country` VALUES (9, 'fr-co', 'Corse');
INSERT INTO `xfguestbook_country` VALUES (10, 'fr-fc', 'Franche-Comté');
INSERT INTO `xfguestbook_country` VALUES (11, 'fr-hn', 'Haute-Normandie');
INSERT INTO `xfguestbook_country` VALUES (12, 'fr-if', 'Ile de France');
INSERT INTO `xfguestbook_country` VALUES (13, 'fr-lr', 'Languedoc-Roussillon');
INSERT INTO `xfguestbook_country` VALUES (14, 'fr-li', 'Limousin');
INSERT INTO `xfguestbook_country` VALUES (15, 'fr-lo', 'Lorraine');
INSERT INTO `xfguestbook_country` VALUES (16, 'fr-mp', 'Midi-Pyrénées');
INSERT INTO `xfguestbook_country` VALUES (17, 'fr-np', 'Nord-Pas de Calais');
INSERT INTO `xfguestbook_country` VALUES (18, 'fr-pa', 'Provence-Alpes-Côte d\'azur');
INSERT INTO `xfguestbook_country` VALUES (19, 'fr-pi', 'Picardie');
INSERT INTO `xfguestbook_country` VALUES (20, 'fr-pl', 'Pays de Loire');
INSERT INTO `xfguestbook_country` VALUES (21, 'fr-pc', 'Poitou-Charentes');
INSERT INTO `xfguestbook_country` VALUES (22, 'fr-ra', 'Rhône-Alpes');
INSERT INTO `xfguestbook_country` VALUES (23, 'fr-gp', 'Guadeloupe');
INSERT INTO `xfguestbook_country` VALUES (24, 'fr-re', 'Réunion');
INSERT INTO `xfguestbook_country` VALUES (25, 'fr', 'Guyanne');
INSERT INTO `xfguestbook_country` VALUES (26, 'fr-my', 'Mayotte');
INSERT INTO `xfguestbook_country` VALUES (27, 'fr-pm', 'Saint Pierre et Miquelon');
INSERT INTO `xfguestbook_country` VALUES (28, 'fr', 'Nouvelle Calédonie');
INSERT INTO `xfguestbook_country` VALUES (29, 'fr-wf', 'Wallis et Futuna');
INSERT INTO `xfguestbook_country` VALUES (30, 'fr-pf', 'Polynésie Française');
INSERT INTO `xfguestbook_country` VALUES (31, 'fr-ma', 'Martinique');
